### ISSUE TITLE
Unsupported Resource Handlee Runtime [java8]

### ISSUE THREAD

**Issue by mrugankray** [aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner#62] opened 2024-02-16 06:06 UTC
Getting this error while registering this -> Unsupported Resource Handler Runtime [java8] for AwsUtility::Cloudformation::CommandRunner - Runtime is Depricated

**Comment by gardnerdez** [comment] 2024-02-28 21:57
I'm having the same issue, cant get pass the outdated java

AwsUtility::Cloudformation::CommandRunner - Runtime is Deprecated

**Comment by rajrishi7817** [comment] 2024-03-05 12:27
Still facing the issue

**Comment by danf22** [comment] 2024-03-05 19:10
Same issue here.

**Comment by transferhp** [comment] 2024-03-08 00:26
Hi can we review the change request and try to approve it soon as the issue still exists now.

**Comment by shantgup** [comment] 2024-03-09 01:39
The pull request is merged, the issue is resolved. You can compile and install it by running the following commands.

```
git clone https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner.git

cd aws-cloudformation-resource-providers-awsutilities-commandrunner

./scripts/build.sh
```

You'll need Java, Maven and CFN CLI installed, I have the following versions running. 

```
$ cfn --version
cfn 0.2.35

$ mvn -version
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /opt/homebrew/Cellar/maven/3.9.6/libexec
Java version: 19.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-19.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "14.1.1", arch: "aarch64", family: "mac"

$ java -version
java 19.0.2 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```

Please let me know if you run into any issues. Appreciate your patience while we fixed this!

**Closed** 2024-03-09 01:41 UTC

**Comment by shantgup** [comment] 2024-03-09 18:06
Register.sh is fixed! Everything works like before now.

**Comment by mrugankray** [comment] 2024-03-09 18:36
> Register.sh is fixed! Everything works like before now.

Thanks for fixing man!
